all:
    hosts:
        ca32:
            ansible_ssh_host: ca32.lvn.broadcom.net
            ansible_python_interpreter: /C/zConnect/usr/lpp/IBM/izoda/anaconda/bin/python
            ansible_shell_executable: /C/Rocket/bin/bash
            zowe_profile: ca32
            zmf_host: ca32.lvn.broadcom.net
            zmf_port: 1443
